# Generated by Django 3.2.14 on 2022-08-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='intended_major',
            field=models.BooleanField(blank=True),
        ),
    ]
