# Generated by Django 3.2.15 on 2022-08-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_db', '0004_alter_interview_standing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='image',
            field=models.ImageField(blank=True, default='', help_text='Image should be 1875 x 2882 (any orientation), saved as an optimized High Quality (60) JPEG.', null=True, upload_to='interview_db_images'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='Describe the image in detail so that a non-sighted user might also get that personal connection.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='description',
            field=models.CharField(help_text='Provide a <strong>brief</strong> description. Something that could be the title attribute of the link.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='story',
            name='related_resource_links',
            field=models.ManyToManyField(blank=True, help_text='Select any resources that would be useful or relevant in this situation, whether mentioned in the story or not.<br/>', to='interview_db.ResourceLink'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_order_position',
            field=models.IntegerField(help_text='Logical position of story within context of other stories w/in interview. <strong>Must be unique</strong> to other stories of the same interview!'),
        ),
    ]
