# Generated by Django 3.2.16 on 2024-01-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_db', '0007_collection_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='codes',
            field=models.ManyToManyField(blank=True, to='interview_db.Code'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='question',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='subcodes',
            field=models.ManyToManyField(blank=True, to='interview_db.SubCode'),
        ),
    ]
