# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-20 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hx_toolkit', '0004_article_image_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_alt_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
